package com.dfu.downloader.type;

public enum DfuStateType {
	QUERY,
	INITIALIZE,
	BEGIN_UPDATE,
	START_SECTION_UPDATE,
	SECTION_UPDATE,
	END_SECTION_UPDATE,
	END_UPDATE,
	BEGIN_VALIDATION,
	START_SECTION_VALIDATION,
	VALIDATE_SECTION,
	END_SECTION_VALIDATION,
	END_VALIDATION,
	COMPLETE_UPDATE,
	NULL
}
